# Trained with A100 (80 GB) x 1 GPUs.
encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

decoder: transducer
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 512
    dropout: 0.1
    dropout_embed: 0.2

joint_net_conf:
    joint_space_size: 640

model: contextualbiasing_sampling_espnet
model_conf:
    ctc_weight: 0.0
    report_cer: False
    report_wer: False
    # TCPGen for contextual biasing
    biasinglist: local/rareword_f15.txt
    bmaxlen: 200
    bdrop: 0.0
    battndim: 512
    # special sampling methods
    sdrop: 0.3
    biasing: true
    freeze_enc_dec: true
    biasing_type: 'contextualbiasing'
    sampling_type: 'framelevel_cluster'
    clusters: 10
    topk: 2

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

seed: 2022
num_workers: 8
batch_type: numel
batch_bins: 1500000
accum_grad: 32
max_epoch: 150
patience: none
init: none
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10
use_amp: false

optim: adam
optim_conf:
    lr: 0.0005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5
